name: Code Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  covr:
    runs-on: ubuntu-18.04
    container: cfgo/gh-actions:base
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Query dependencies
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
          remotes::install_cran("htmltools")
          remotes::install_cran("DT")
        shell: Rscript {0}

      - name: Unit-test coverage
        run: |-
          Rscript -e 'tests <- covr::package_coverage(type = "tests")
            path_tests <- file.path(tempdir(), "covr-tests-report.html")
            Sys.setenv(ENV_PATH_TESTS=path_tests)
            Sys.getenv("ENV_PATH_TESTS")
            covr::report(x = tests, file = path_tests, browse = FALSE)
            if (covr::coverage_to_list(tests)$totalcoverage < 100) stop("Code Coverage not 100%")'
            
          echo "::set-env name=DEPLOY_PATH::$(Rscript -e "path <- file.path(tempdir(), "report.html"); covr::report(covr::package_coverage(type = "tests"), file = path, browse = FALSE); cat(path)")"

      - name: Example coverage
        run: |
          examples <- covr::package_coverage(type = c("examples"))
          path_examples <- file.path(tempdir(), "covr-examples-report.html")
          Sys.setenv(ENV_PATH_EXAMPLES=path_examples)
          covr::report(x = examples, file = path_examples, browse = FALSE)
        shell: Rscript {0}
        
      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: Coverage Reports
          path: ${{ env.DEPLOY_PATH }}