name: Code Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  covr:
    runs-on: ubuntu-18.04
    container: cfgo/gh-actions:base
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Query dependencies
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
          remotes::install_cran("htmltools")
          remotes::install_cran("DT")
        shell: Rscript {0}

      - name: Unit test coverage
        run: |
          tests <- covr::package_coverage(type = "tests")
          tests_list <- covr::coverage_to_list(tests)
          warning("Total Coverage: ", tests_list$totalcoverage, "%")
          
          tests_df <- as.data.frame(tests_list$filecoverage)
          for(i in 1:nrow(tests_df)) {
            warning(row.names(tests_df)[i], ": ", tests_df[i,], "%")
          }
          
          path_tests <- file.path(tempdir(), "covr-tests-report.html")
          covr::report(x = tests, file = path_tests, browse = FALSE)
          
          if (covr::coverage_to_list(tests)$totalcoverage < 100) {
            stop("Code Coverage not 100%")
          }
        shell: Rscript {0}
        
      - name: Example coverage
        run: |
          examples <- covr::package_coverage(type = c("examples"))
          examples_list <- covr::coverage_to_list(examples)
          warning("Total Coverage: ", examples_list$totalcoverage, "%")
          
          examples_df <- as.data.frame(examples_list$filecoverage)
          for(i in 1:nrow(examples_df)) {
            warning(row.names(examples_df)[i], ": ", examples_df[i,], "%")
          }
          
          path_examples <- file.path(tempdir(), "covr-examples-report.html")
          covr::report(x = examples, file = path_examples, browse = FALSE)
        shell: Rscript {0}
        
      - name: Print paths
        run: |-
          echo "::set-env name=DEPLOY_PATH_TESTS::$(Rscript -e "cat(path_tests)")"
          echo "::set-env name=DEPLOY_PATH_EXAMPLES::$(Rscript -e "cat(path_examples)")"
          
      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: Coverage Reports
          path: ${{ env.DEPLOY_PATH_TESTS }}