name: Docker

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: cfgo/cfgoTest
    
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")'
        
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-results
          path: check